models/Driver.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "drivers".
 *
 * @property integer $id
 * @property string $name
 * @property string $surname
 * @property integer $phone
 * @property integer $age
 * @property integer $active
 */
class Driver extends \yii\db\ActiveRecord {

    public $models = [];

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'drivers';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['name', 'surname', 'phone', 'age', 'active'], 'required'],
            [['phone', 'age', 'active'], 'integer'],
            [['name', 'surname'], 'string', 'max' => 50],
            [['models'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'surname' => 'Фамилия',
            'phone' => 'Телефон',
            'age' => 'Возраст',
            'active' => 'Активен',
            'models' => 'Модели автобусов'
        ];
    }

    public function getModels() {
        $this->models = ArrayHelper::getColumn($this->hasMany(Bus2driver::className(), ['id_driver' => 'id'])->all(), 'id_bus');
    }

    public function afterSave($insert, $changedAttributes) {
        Bus2driver::deleteAll(['id_driver' => $this->id]);
        if ($this->models) {
            $values = [];
            foreach ($this->models as $id) {
                $values[] = [$this->id, $id];
            }
            self::getDb()->createCommand()
                    ->batchInsert(Bus2driver::tableName(), ['id_driver', 'id_bus'], $values)->execute();
        }

        parent::afterSave($insert, $changedAttributes);
    }

}

controllers/DriverController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Driver;
use app\models\DriverSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Bus;
use app\models\Bus2driver;

/**
 * DriverController implements the CRUD actions for Driver model.
 */
class DriverController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Driver models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new DriverSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Driver model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Driver model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Driver();
        $bus_list = Bus::bus_list();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                        'model' => $model,
                        'bus_list' => $bus_list,
            ]);
        }
    }

    /**
     * Updates an existing Driver model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $bus_list = Bus::bus_list();
        $model->getModels();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                        'model' => $model,
                        'bus_list' => $bus_list,
            ]);
        }
    }

    /**
     * Deletes an existing Driver model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();
        Bus2driver::deleteAll(['id_driver'=>$id]);
        return $this->redirect(['index']);
    }
    
    public function actionActive($id){
        $model = $this->findModel($id);
        $model->active = $model->active?0:1;
        $model->save();
        return $model->active;
    }

    protected function findModel($id) {
        if (($model = Driver::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

}

views/driver/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Driver */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="driver-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="col-lg-4 col-sm-6">
        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    </div>
    <div class="col-lg-4 col-sm-6">
        <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>
    </div>
    <div class="col-lg-2 col-sm-6">
        <?= $form->field($model, 'phone')->textInput() ?>
    </div>
    <div class="col-lg-2 col-sm-6">
        <?= $form->field($model, 'age')->textInput() ?>
    </div>
    <div class="col-lg-12 col-sm-12">
        <?=
        $form->field($model, 'models')->widget(Select2::classname(), [
            'data' => $bus_list,
            'language' => 'ru',
            'options' => ['placeholder' => 'Выберите модели'],
            'pluginOptions' => [
                'allowClear' => true,
                'multiple' => true
            ],
        ])
        ?>
    </div>
    <div class="col-lg-12 col-sm-12">
        <?= $form->field($model, 'active')->checkbox() ?>
    </div>
    <div class="form-group col-lg-12 col-sm-12">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/driver/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DriverSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="driver-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'surname') ?>

    <?= $form->field($model, 'phone') ?>

    <?= $form->field($model, 'age') ?>

    <?php // echo $form->field($model, 'active') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/driver/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Driver */

$this->title = 'Новый водитель';
$this->params['breadcrumbs'][] = ['label' => 'Водители', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="driver-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
        'bus_list' => $bus_list,
    ])
    ?>

</div>

views/driver/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/driver/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\models\DriverSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->registerJsFile('/js/updateActive.js',['depends' => [\yii\web\JqueryAsset::className()]]);
$this->title = 'Водители';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="driver-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Новый водитель', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            //'id',
            'name',
            'surname',
            'phone',
            'age',
            [
                'class' => \yii\grid\DataColumn::className(),
                'attribute' => 'active',
                'format' => 'raw',
                'filter' => false,
                'value' => function ($model, $index, $widget) {
                    return Html::checkbox("active[]", $model->active, ['class'=>'active','value' => $model->active,'data'=>['url'=>Url::to(['driver/active','id'=>$index]),'id'=>$index]]);
                },
                    ],
                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]);
            ?>

</div>

views/driver/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Driver */

$this->title = 'Изменить водителя: ' . ' ' . $model->surname . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Водители', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="driver-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
        'bus_list' => $bus_list,
    ])
    ?>

</div>

views/driver/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Driver */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Водители', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="driver-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены что хотите удалить?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'surname',
            'phone',
            'age',
            'active',
        ],
    ]) ?>

</div>